# Generated by Django 2.0.3 on 2018-07-24 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionadministrator',
            name='forum_administrator_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionadministrator',
            name='forum_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionForum'),
        ),
    ]
