# Generated by Django 2.0.5 on 2018-05-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_common_member_count_common_member_field_forum_common_member_field_home_member_crime'),
        ('article', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'forum-admin',
            },
        ),
        migrations.CreateModel(
            name='Forum_attachemnt',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('tid', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.forum_post')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.common_member')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.AlterModelOptions(
            name='forum_forum',
            options={'verbose_name': 'forum', 'verbose_name_plural': 'forums'},
        ),
        migrations.AddField(
            model_name='forum_forum',
            name='lastpostid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.forum_post'),
        ),
    ]
