# Generated by Django 2.0.6 on 2018-07-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20180730_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionforum',
            name='block',
            field=models.CharField(choices=[('a', 'A区－－部门组织'), ('b', 'B区－－信息论坛'), ('c', 'B区－－我们的家'), ('d', 'B区－－出国留学'), ('e', 'B区－－学术科学'), ('f', 'B区－－文化艺术'), ('g', 'B区－－休闲感性'), ('h', 'B区－－体育健身'), ('i', 'B区－－瀚海特区'), ('j', 'B区－－本站系统')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
