# Generated by Django 2.0.6 on 2018-07-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='group_name',
            new_name='channel_name',
        ),
    ]
