# Generated by Django 2.0.6 on 2018-07-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatlog_chat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='chat_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
