# Generated by Django 2.0.6 on 2018-08-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180802_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='django-db-models-fields-charfield', max_length=500),
        ),
    ]
