# Generated by Django 2.0.6 on 2018-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180730_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
