# Generated by Django 2.0.6 on 2018-07-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180730_1413'),
        ('article', '0002_auto_20180730_1737'),
    ]

    operations = [
    ]
