# Generated by Django 2.0.7 on 2018-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180728_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
