# Generated by Django 2.0.7 on 2018-07-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_ueditor_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
    ]
