# Generated by Django 2.0.7 on 2018-07-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_comment_commentator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
    ]
