# Generated by Django 2.0.7 on 2018-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180729_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='comment_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
