# Generated by Django 2.0.7 on 2018-07-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180729_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='counter',
            field=models.IntegerField(),
        ),
    ]
