# Generated by Django 2.0.5 on 2018-06-04 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_member_star',
            name='star_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 21, 45, 54, 56201)),
        ),
    ]
