# Generated by Django 2.0.6 on 2018-08-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_member',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='django-db-models-fields-charfield', max_length=100),
        ),
    ]
