# Generated by Django 2.0.6 on 2018-07-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_member',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='portraits'),
        ),
        migrations.AddField(
            model_name='common_member',
            name='show_gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='follower_pair',
            name='follow_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='common_member',
            name='gender',
            field=models.CharField(choices=[('m', '男'), ('f', '女')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='common_member_star',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.forum_post'),
        ),
        migrations.AlterField(
            model_name='common_member_star',
            name='spid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.forum_school_info'),
        ),
    ]
