# Generated by Django 2.0.5 on 2018-05-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='common_member_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.IntegerField(max_length=12)),
                ('threads', models.IntegerField(max_length=12)),
                ('digestposts', models.IntegerField(max_length=10)),
                ('doings', models.IntegerField(max_length=10)),
                ('blogs', models.IntegerField(max_length=10)),
                ('albums', models.IntegerField(max_length=10)),
                ('sharings', models.IntegerField(max_length=14)),
                ('attachsize', models.IntegerField(max_length=15)),
                ('views', models.IntegerField(max_length=15)),
                ('oltime', models.IntegerField(max_length=12)),
                ('todayattachs', models.IntegerField(max_length=12)),
                ('todayattachsize', models.IntegerField(max_length=15)),
                ('blacklist', models.IntegerField(max_length=12)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.common_member')),
            ],
        ),
        migrations.CreateModel(
            name='common_member_field_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupterms', models.CharField(choices=[('ST', 'student'), ('TE', 'teacher')], default='ST', max_length=2)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.common_member')),
            ],
        ),
        migrations.CreateModel(
            name='common_member_field_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spacename', models.CharField(max_length=256)),
                ('domain', models.CharField(max_length=15)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.common_member')),
            ],
        ),
        migrations.CreateModel(
            name='member_crime',
            fields=[
                ('cid', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('dateline', models.TimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.common_member_action_log')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.common_member')),
            ],
        ),
    ]
