# Generated by Django 2.0.6 on 2018-07-31 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20180730_1946'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commom_member_watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.DateTimeField(auto_now_add=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionForum')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='common_member_star',
            name='star_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member_crime',
            name='dateline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
