# Generated by Django 2.0.6 on 2018-07-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180731_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commom_member_watch',
            old_name='section_id',
            new_name='sectionid',
        ),
    ]
