# Generated by Django 2.0.6 on 2018-06-09 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180604_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common_member',
            name='accessmasks',
        ),
        migrations.RemoveField(
            model_name='common_member',
            name='allowadmincp',
        ),
        migrations.RemoveField(
            model_name='common_member',
            name='avatarstatus',
        ),
        migrations.RemoveField(
            model_name='common_member',
            name='email_status',
        ),
        migrations.RemoveField(
            model_name='common_member',
            name='freeze',
        ),
        migrations.RemoveField(
            model_name='common_member',
            name='status',
        ),
        migrations.AlterField(
            model_name='common_member_star',
            name='star_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 13, 28, 54, 960605)),
        ),
    ]
