# Generated by Django 2.0.6 on 2018-06-09 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180609_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_member_star',
            name='star_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 18, 17, 50, 324605, tzinfo=utc)),
        ),
    ]
