# Generated by Django 2.0.6 on 2018-07-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180731_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commom_member_watch',
            old_name='sectionid',
            new_name='section',
        ),
    ]
