# Generated by Django 2.0.6 on 2018-06-10 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180609_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_member_star',
            name='star_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 3, 24, 58, 461782, tzinfo=utc)),
        ),
    ]
