# Generated by Django 2.0.6 on 2018-06-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180611_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_member_star',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.forum_post', unique=True),
        ),
        migrations.AlterField(
            model_name='common_member_star',
            name='spid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.forum_school_info', unique=True),
        ),
    ]
